### ISSUE TITLE
Add links to online recordings of songs

### ISSUE THREAD

**Issue by morosebose** [v9y/giit#90]
It would be nice if in addition to the lyrics, the giitaayan page included or embedded a link on an online version of the song on YouTube or some such site. In the case of songs where there are different versions (tandems, different stanzas, etc), more than one link would be nice.

Ideally, an end-user who looks up the lyrics would be able to hear the song at the giitayan site (if embedded), or at least click a link to hear the song elsewhere.

A "report broken link" link would also be needed in case a recording gets taken down.

**Comment by v9y** [comment]
I have thought about it in the past and have decided to not do it. Recently, it also seems to bring copyright issues. It is becoming increasingly common for audio companies (in their stupid arrogance) to report even such links (and as a result the whole site) as violations. I know of sites that got their domains banned in India because of this.

**Comment by morosebose** [comment]
> I have thought about it in the past and have decided to not do it. 

k
